#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v19
# autospec commit: a62a849262cd
#
Name     : xsimd
Version  : 13.0.0
Release  : 1
URL      : https://github.com/xtensor-stack/xsimd/archive/13.0.0/xsimd-13.0.0.tar.gz
Source0  : https://github.com/xtensor-stack/xsimd/archive/13.0.0/xsimd-13.0.0.tar.gz
Summary  : xsimd provides a unified means for using SIMD features for library authors..
Group    : Development/Tools
License  : BSD-3-Clause
Requires: xsimd-license = %{version}-%{release}
BuildRequires : buildreq-cmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# ![xsimd](docs/source/xsimd.svg)
[![GHA android](https://github.com/xtensor-stack/xsimd/actions/workflows/android.yml/badge.svg)](https://github.com/xtensor-stack/xsimd/actions/workflows/android.yml)
[![GHA cross-rvv](https://github.com/xtensor-stack/xsimd/actions/workflows/cross-rvv.yml/badge.svg)](https://github.com/xtensor-stack/xsimd/actions/workflows/cross-rvv.yml)
[![GHA cross-sve](https://github.com/xtensor-stack/xsimd/actions/workflows/cross-sve.yml/badge.svg)](https://github.com/xtensor-stack/xsimd/actions/workflows/cross-sve.yml)
[![GHA cross](https://github.com/xtensor-stack/xsimd/actions/workflows/cross.yml/badge.svg)](https://github.com/xtensor-stack/xsimd/actions/workflows/cross.yml)
[![GHA cxx-no-exceptions](https://github.com/xtensor-stack/xsimd/actions/workflows/cxx-no-exceptions.yml/badge.svg)](https://github.com/xtensor-stack/xsimd/actions/workflows/cxx-no-exceptions.yml)
[![GHA cxx-versions](https://github.com/xtensor-stack/xsimd/actions/workflows/cxx-versions.yml/badge.svg)](https://github.com/xtensor-stack/xsimd/actions/workflows/cxx-versions.yml)
[![GHA emscripten](https://github.com/xtensor-stack/xsimd/actions/workflows/emscripten.yml/badge.svg)](https://github.com/xtensor-stack/xsimd/actions/workflows/emscripten.yml)
[![GHA linux](https://github.com/xtensor-stack/xsimd/actions/workflows/linux.yml/badge.svg)](https://github.com/xtensor-stack/xsimd/actions/workflows/linux.yml)
[![GHA macos](https://github.com/xtensor-stack/xsimd/actions/workflows/macos.yml/badge.svg)](https://github.com/xtensor-stack/xsimd/actions/workflows/macos.yml)
[![GHA windows](https://github.com/xtensor-stack/xsimd/actions/workflows/windows.yml/badge.svg)](https://github.com/xtensor-stack/xsimd/actions/workflows/windows.yml)
[![Documentation Status](http://readthedocs.org/projects/xsimd/badge/?version=latest)](https://xsimd.readthedocs.io/en/latest/?badge=latest)
[![Join the Gitter Chat](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/QuantStack/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

%package dev
Summary: dev components for the xsimd package.
Group: Development
Provides: xsimd-devel = %{version}-%{release}
Requires: xsimd = %{version}-%{release}

%description dev
dev components for the xsimd package.


%package license
Summary: license components for the xsimd package.
Group: Default

%description license
license components for the xsimd package.


%prep
%setup -q -n xsimd-13.0.0
cd %{_builddir}/xsimd-13.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1726100051
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1726100051
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xsimd
cp %{_builddir}/xsimd-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/xsimd/fdd09d28bfe251c8ded2a4c4f57ea47f2e123b94 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/xsimd/arch/generic/xsimd_generic_arithmetic.hpp
/usr/include/xsimd/arch/generic/xsimd_generic_complex.hpp
/usr/include/xsimd/arch/generic/xsimd_generic_details.hpp
/usr/include/xsimd/arch/generic/xsimd_generic_logical.hpp
/usr/include/xsimd/arch/generic/xsimd_generic_math.hpp
/usr/include/xsimd/arch/generic/xsimd_generic_memory.hpp
/usr/include/xsimd/arch/generic/xsimd_generic_rounding.hpp
/usr/include/xsimd/arch/generic/xsimd_generic_trigo.hpp
/usr/include/xsimd/arch/xsimd_avx.hpp
/usr/include/xsimd/arch/xsimd_avx2.hpp
/usr/include/xsimd/arch/xsimd_avx512bw.hpp
/usr/include/xsimd/arch/xsimd_avx512cd.hpp
/usr/include/xsimd/arch/xsimd_avx512dq.hpp
/usr/include/xsimd/arch/xsimd_avx512er.hpp
/usr/include/xsimd/arch/xsimd_avx512f.hpp
/usr/include/xsimd/arch/xsimd_avx512ifma.hpp
/usr/include/xsimd/arch/xsimd_avx512pf.hpp
/usr/include/xsimd/arch/xsimd_avx512vbmi.hpp
/usr/include/xsimd/arch/xsimd_avx512vnni_avx512bw.hpp
/usr/include/xsimd/arch/xsimd_avx512vnni_avx512vbmi.hpp
/usr/include/xsimd/arch/xsimd_avxvnni.hpp
/usr/include/xsimd/arch/xsimd_constants.hpp
/usr/include/xsimd/arch/xsimd_emulated.hpp
/usr/include/xsimd/arch/xsimd_fma3_avx.hpp
/usr/include/xsimd/arch/xsimd_fma3_avx2.hpp
/usr/include/xsimd/arch/xsimd_fma3_sse.hpp
/usr/include/xsimd/arch/xsimd_fma4.hpp
/usr/include/xsimd/arch/xsimd_generic.hpp
/usr/include/xsimd/arch/xsimd_generic_fwd.hpp
/usr/include/xsimd/arch/xsimd_i8mm_neon64.hpp
/usr/include/xsimd/arch/xsimd_isa.hpp
/usr/include/xsimd/arch/xsimd_neon.hpp
/usr/include/xsimd/arch/xsimd_neon64.hpp
/usr/include/xsimd/arch/xsimd_rvv.hpp
/usr/include/xsimd/arch/xsimd_scalar.hpp
/usr/include/xsimd/arch/xsimd_sse2.hpp
/usr/include/xsimd/arch/xsimd_sse3.hpp
/usr/include/xsimd/arch/xsimd_sse4_1.hpp
/usr/include/xsimd/arch/xsimd_sse4_2.hpp
/usr/include/xsimd/arch/xsimd_ssse3.hpp
/usr/include/xsimd/arch/xsimd_sve.hpp
/usr/include/xsimd/arch/xsimd_wasm.hpp
/usr/include/xsimd/config/xsimd_arch.hpp
/usr/include/xsimd/config/xsimd_config.hpp
/usr/include/xsimd/config/xsimd_cpuid.hpp
/usr/include/xsimd/config/xsimd_inline.hpp
/usr/include/xsimd/math/xsimd_rem_pio2.hpp
/usr/include/xsimd/memory/xsimd_aligned_allocator.hpp
/usr/include/xsimd/memory/xsimd_alignment.hpp
/usr/include/xsimd/types/xsimd_all_registers.hpp
/usr/include/xsimd/types/xsimd_api.hpp
/usr/include/xsimd/types/xsimd_avx2_register.hpp
/usr/include/xsimd/types/xsimd_avx512bw_register.hpp
/usr/include/xsimd/types/xsimd_avx512cd_register.hpp
/usr/include/xsimd/types/xsimd_avx512dq_register.hpp
/usr/include/xsimd/types/xsimd_avx512er_register.hpp
/usr/include/xsimd/types/xsimd_avx512f_register.hpp
/usr/include/xsimd/types/xsimd_avx512ifma_register.hpp
/usr/include/xsimd/types/xsimd_avx512pf_register.hpp
/usr/include/xsimd/types/xsimd_avx512vbmi_register.hpp
/usr/include/xsimd/types/xsimd_avx512vnni_avx512bw_register.hpp
/usr/include/xsimd/types/xsimd_avx512vnni_avx512vbmi_register.hpp
/usr/include/xsimd/types/xsimd_avx_register.hpp
/usr/include/xsimd/types/xsimd_avxvnni_register.hpp
/usr/include/xsimd/types/xsimd_batch.hpp
/usr/include/xsimd/types/xsimd_batch_constant.hpp
/usr/include/xsimd/types/xsimd_emulated_register.hpp
/usr/include/xsimd/types/xsimd_fma3_avx2_register.hpp
/usr/include/xsimd/types/xsimd_fma3_avx_register.hpp
/usr/include/xsimd/types/xsimd_fma3_sse_register.hpp
/usr/include/xsimd/types/xsimd_fma4_register.hpp
/usr/include/xsimd/types/xsimd_generic_arch.hpp
/usr/include/xsimd/types/xsimd_i8mm_neon64_register.hpp
/usr/include/xsimd/types/xsimd_neon64_register.hpp
/usr/include/xsimd/types/xsimd_neon_register.hpp
/usr/include/xsimd/types/xsimd_register.hpp
/usr/include/xsimd/types/xsimd_rvv_register.hpp
/usr/include/xsimd/types/xsimd_sse2_register.hpp
/usr/include/xsimd/types/xsimd_sse3_register.hpp
/usr/include/xsimd/types/xsimd_sse4_1_register.hpp
/usr/include/xsimd/types/xsimd_sse4_2_register.hpp
/usr/include/xsimd/types/xsimd_ssse3_register.hpp
/usr/include/xsimd/types/xsimd_sve_register.hpp
/usr/include/xsimd/types/xsimd_traits.hpp
/usr/include/xsimd/types/xsimd_utils.hpp
/usr/include/xsimd/types/xsimd_wasm_register.hpp
/usr/include/xsimd/xsimd.hpp
/usr/lib64/cmake/xsimd/xsimdConfig.cmake
/usr/lib64/cmake/xsimd/xsimdConfigVersion.cmake
/usr/lib64/cmake/xsimd/xsimdTargets.cmake
/usr/lib64/pkgconfig/xsimd.pc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xsimd/fdd09d28bfe251c8ded2a4c4f57ea47f2e123b94
